### ISSUE TITLE
Support unicode characters when "Export"

### ISSUE THREAD

**Issue by psychelzh** [EFanZh/Graphviz-Preview#17]
Unicode characters are not exported correctly.

A minimal example:

```dot
digraph test {
    A [label = "测试"]
    B [label = "Test"]
    A -> B
}
```

The `Export`ed image file (the unicode character "测试" disappeared):

![test](https://user-images.githubusercontent.com/13306020/49205785-103b8380-f3eb-11e8-8396-b5cfbc20816f.png)

**Comment by EFanZh** [comment]
Try to [set the font](https://www.graphviz.org/doc/info/attrs.html#a:fontname) explicitly.

The result you were seeing might be caused by the default font not being able to handle unicode characters. The preview should be fine because it is using SVG format which can automatically fallback to using a font in your system that supports the unicode characters. If you export the image in a format other than SVG, and you didn’t set the font properly, you may get what you were seeing.
